version: 2
jobs:
  build:
    working_directory: ~/gladeo
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
    - run:
        name: update-npm
        command: sudo npm install -g npm@latest
    - run:
        name: install-yarn
        command: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run:
        name: install-dependencies
        command: yarn install
    - run:
        name: test
        command: yarn test
workflows:
  version: 2
  workflow:
    jobs:
    - build